# Generated by Django 4.1.4 on 2022-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_long_name', models.CharField(help_text='E.g Junior Secondary 1', max_length=50, unique=True)),
                ('class_short_name', models.CharField(help_text='E.g JSS1', max_length=30)),
                ('class_name_in_numeric', models.IntegerField(help_text='E.g 1,2,4,5 etc', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['class_name_in_numeric'],
            },
        ),
    ]
